/* ============================================================
 * 栈知映 · 技能树数据(4 个方向,每方向 >= 40 节点)
 * depth_level 已按依赖拓扑排序,严格由浅入深(1 最浅)
 * 每个节点含严格学习目标、关键概念与通过标准
 * ============================================================ */

function N(id, title, icon, cat, depth, rd, status, order, obj, concepts, ev) {
  return { id: id, title: title, icon: icon, category: cat, depth_level: depth,
    recommended_depth: rd, status: status, order: order,
    learning_objectives: obj, key_concepts: concepts, observable_evidence: ev, description: null };
}
function E(s, t) { return { id: s + '>' + t, source: s, target: t }; }

var DEPTH_LABELS = {"Recognize":"认识","Understand":"理解","Use":"应用","Transfer":"迁移","DeepMastery":"深度掌握"};
var STATUS_LABELS = {"not_started":"未学习","in_progress":"正在学习","completed":"已完成","mastered":"已掌握"};

var TREES = {
  frontend: {
    tree: {"id":"frontend","topic":"前端开发","title":"前端开发工程师技能树","description":"从 HTML/CSS/JS 基础到框架、工程化、性能与安全的完整前端进阶路线(42 节点)。"},
    current: "typescript",
    nodes: [
      N("html", "HTML 语义化", "📄", "HTML", 1, "Understand", "mastered", 0, ["掌握 HTML5 语义化标签(section/article/nav/main 等)的准确使用场景","能构建结构清晰、层级合理的页面骨架","理解文档大纲、可访问性(ARIA)与 SEO 的关系"], ["语义化","ARIA"], ["口述各语义标签的适用场景并给出正反例","页面通过无障碍与结构校验"]),
      N("css-box", "CSS 盒模型与选择器", "🎨", "CSS", 2, "Understand", "mastered", 0, ["彻底掌握标准盒模型与替代盒模型(content-box/border-box)的差异","掌握选择器优先级(特异性)的计算规则","理解 margin 合并与 BFC 的形成条件"], ["盒模型","特异性","BFC"], ["准确预测任意选择器的生效结果","解释 margin 塌陷并给出三种解决方案"]),
      N("css-cascade", "CSS 层叠与继承", "🎨", "CSS", 3, "Understand", "mastered", 0, ["理解层叠、继承与优先级三大机制的相互作用","掌握 CSS 自定义属性(变量)的继承与作用域","能用变量实现主题与设计令牌"], ["层叠","继承","CSS 变量"], ["解释某个样式为何生效/失效","用 CSS 变量实现一键换肤"]),
      N("flexbox", "Flexbox 布局", "📐", "CSS", 3, "Use", "mastered", 0, ["熟练使用主轴/交叉轴与对齐属性完成布局","掌握 flex-grow/shrink/basis 的伸缩计算","能实现居中、等分、圣杯等常见布局"], ["主轴交叉轴","伸缩计算"], ["复刻典型导航栏与卡片网格布局并说明对齐逻辑"]),
      N("grid", "Grid 布局", "📐", "CSS", 4, "Use", "mastered", 0, ["掌握 grid-template 与命名区域布局","理解 fr 单位、隐式网格与 auto-placement","能实现复杂二维布局"], ["网格轨道","命名区域"], ["用 Grid 复刻一个后台 dashboard 布局"]),
      N("responsive", "响应式设计", "📱", "CSS", 5, "Use", "mastered", 0, ["掌握媒体查询、断点设计与移动优先策略","理解视口、相对单位与响应式图片","能实现多端自适应的完整布局"], ["媒体查询","移动优先"], ["让同一页面在手机/平板/桌面正确显示"]),
      N("js-basic", "JavaScript 语法基础", "⚙️", "JS", 1, "Understand", "mastered", 0, ["掌握变量、运算符、流程控制与循环","理解 let/const/var 的差异与变量提升","能独立编写结构化的基础脚本"], ["作用域","变量提升"], ["独立完成一个交互小脚本"]),
      N("js-types", "数据类型与类型转换", "⚙️", "JS", 2, "Understand", "mastered", 0, ["掌握七种原始类型与引用类型的区别","理解隐式/显式类型转换规则","掌握 == 与 === 的差异与适用取舍"], ["原始类型","类型转换"], ["准确预测复杂表达式的类型转换结果"]),
      N("js-func", "函数与作用域", "⚙️", "JS", 2, "Understand", "mastered", 0, ["掌握函数声明、函数表达式与箭头函数","理解作用域链与词法作用域","掌握默认参数、剩余参数与参数解构"], ["作用域链","箭头函数"], ["解释一段嵌套函数的作用域查找过程"]),
      N("js-object", "对象与原型链", "🧬", "JS", 3, "Understand", "mastered", 0, ["理解对象、原型与原型链的机制","掌握 Object 常用方法与属性描述符","能用原型实现继承并理解 class 语法糖"], ["原型链","继承"], ["画出原型链并解释 instanceof 的原理"]),
      N("js-array", "数组与字符串方法", "📚", "JS", 3, "Use", "mastered", 0, ["熟练使用 map/filter/reduce/some/every 等数组方法","掌握字符串常用操作与正则基础","能链式处理数据"], ["map/filter/reduce","正则"], ["用数组方法链式实现一次数据清洗与统计"]),
      N("js-closure", "闭包与高阶函数", "🎁", "JS", 3, "Use", "mastered", 0, ["深刻理解闭包的形成机制与内存影响","掌握高阶函数、柯里化与函数组合","能实现防抖与节流"], ["闭包","柯里化","防抖节流"], ["手写防抖与节流并说明应用场景","解释闭包的内存泄漏与规避"]),
      N("js-this", "this 绑定规则", "🎯", "JS", 3, "Understand", "mastered", 0, ["掌握 this 的四条绑定规则(默认/隐式/显式/new)与优先级","理解箭头函数 this 的词法继承","能准确判断任意调用场景下的 this"], ["绑定规则","箭头函数 this"], ["准确预测任意调用场景下 this 的指向并说明理由"]),
      N("es6", "ES6+ 现代特性", "✨", "JS", 4, "Use", "mastered", 0, ["掌握解构、展开、模板字符串、模块化","理解 Symbol、Map/Set、迭代器等新特性","能把旧代码重构为现代写法"], ["解构","模块化","迭代器"], ["用 ES6+ 特性重构一段旧代码并说明收益"]),
      N("dom", "DOM 操作与事件", "🧩", "浏览器", 5, "Use", "completed", 0, ["熟练进行 DOM 的增删改查与批量操作","掌握事件流、事件委托与自定义事件","理解事件循环与渲染时机的关系"], ["事件委托","事件流"], ["实现一个无框架的交互组件(如轮播/折叠面板)"]),
      N("event-loop", "浏览器事件循环", "🔄", "浏览器", 6, "Understand", "completed", 0, ["理解宏任务、微任务与执行顺序","理解渲染时机与 requestAnimationFrame","能预测混合异步代码的输出顺序"], ["宏任务微任务","rAF"], ["准确预测一段混合异步代码的输出顺序"]),
      N("browser", "浏览器工作原理", "🖥️", "浏览器", 6, "Understand", "completed", 0, ["理解渲染管线(解析/布局/绘制/合成)","理解重排与重绘的触发条件","理解分层与 GPU 合成"], ["渲染管线","重排重绘","合成"], ["解释从输入 URL 到页面展示的完整过程"]),
      N("fetch-api", "网络请求", "🌐", "浏览器", 6, "Use", "completed", 0, ["熟练使用 fetch 与常用请求配置","掌握请求取消(AbortController)与超时处理","理解请求/响应拦截与错误分类"], ["fetch","AbortController"], ["封装一个带重试与超时的请求函数"]),
      N("http", "HTTP 协议", "🌐", "网络", 7, "Understand", "completed", 0, ["掌握 HTTP 方法、状态码与报文结构","理解强缓存与协商缓存机制","理解跨域与 CORS 的解决手段"], ["状态码","缓存","CORS"], ["解释 304 与 401 的区别","排查并解决一次跨域问题"]),
      N("web-storage", "浏览器存储", "💾", "浏览器", 6, "Use", "completed", 0, ["掌握 localStorage/sessionStorage/Cookie/IndexedDB 的差异与选型","理解存储容量限制与安全边界","能落地合适的存储方案"], ["localStorage","IndexedDB"], ["为不同场景选择合适存储并说明理由"]),
      N("promise", "Promise 与异步", "⏳", "异步", 5, "Use", "completed", 0, ["深刻理解 Promise 状态机与链式调用","掌握 Promise 静态方法与并发控制","理解异常穿透与错误传播"], ["状态机","并发控制"], ["手写一个简化版 Promise","实现并发请求数量限制"]),
      N("async-await", "async/await", "⏳", "异步", 6, "Use", "completed", 0, ["掌握 async/await 的语义与错误处理","理解与 Promise 的等价关系","掌握竞态处理与取消"], ["async/await","竞态"], ["封装带超时与取消的异步操作并处理竞态"]),
      N("debugging", "错误处理与调试", "🐛", "工程", 7, "Use", "completed", 0, ["掌握 try/catch 与全局错误捕获","熟练使用断点、性能面板与网络面板","能定位并修复运行时错误"], ["断点调试","性能面板"], ["定位并修复一个线上运行时错误"]),
      N("typescript", "TypeScript", "🔷", "语言", 5, "Use", "in_progress", 0, ["掌握类型注解、接口、类型别名与联合类型","掌握泛型、类型守卫与常用工具类型","能给现有 JS 项目渐进式加类型并消除报错"], ["泛型","类型守卫","工具类型"], ["为一段 JS 补齐类型并消除所有报错"]),
      N("framework-core", "前端框架核心概念", "🧭", "框架", 6, "Use", "in_progress", 0, ["理解组件化、声明式与虚拟 DOM","理解单向数据流与响应式原理","明白框架解决的核心问题与权衡"], ["组件化","虚拟 DOM"], ["用自己的话解释虚拟 DOM 的取舍"]),
      N("react", "React 组件化", "⚛️", "框架", 7, "Use", "not_started", 0, ["掌握函数组件与 JSX 语法","掌握 Props 传递与组件拆分原则","理解组件的生命周期与副作用"], ["函数组件","JSX"], ["拆解一个页面为可复用的函数组件"]),
      N("state-props", "组件状态与 Props", "🔄", "框架", 8, "Use", "not_started", 0, ["掌握 useState 与受控组件","理解 Props 单向流动与状态提升","掌握派生状态并避免冗余状态"], ["useState","状态提升"], ["设计一个复杂表单的状态结构并说明取舍"]),
      N("hooks", "Hooks 深入", "🪝", "框架", 9, "Use", "not_started", 0, ["掌握 useEffect 的依赖与清理","掌握 useMemo/useCallback/useRef 的适用场景","能自定义 Hook 复用逻辑"], ["useEffect","自定义 Hook"], ["封装一个可复用的自定义 Hook"]),
      N("state-mgmt", "状态管理", "🗃️", "框架", 10, "Use", "not_started", 0, ["理解全局状态与局部状态的边界","掌握 Context 与主流状态库的使用","能设计合理、可维护的状态架构"], ["Context","状态架构"], ["为跨组件共享数据选择合适的方案并落地"]),
      N("router", "前端路由", "🔀", "框架", 8, "Use", "not_started", 0, ["掌握路由匹配、懒加载与导航守卫","理解 history 与 hash 两种路由模式","能实现带权限拦截的路由"], ["懒加载","路由守卫"], ["实现带权限拦截的前端路由"]),
      N("forms", "表单处理与校验", "📋", "框架", 10, "Use", "not_started", 0, ["掌握受控/非受控表单的选择","掌握校验方案、错误提示与提交处理","理解表单性能与字段联动"], ["受控表单","校验"], ["实现一个带实时校验的复杂表单"]),
      N("package", "包管理与依赖", "📦", "工程", 5, "Use", "not_started", 0, ["理解 semver、锁文件与依赖树","能处理依赖冲突与依赖安全审计","掌握依赖的合理选型"], ["semver","锁文件"], ["解决一次依赖冲突","升级一个存在漏洞的依赖"]),
      N("vite", "构建工具", "🛠️", "工程", 6, "Use", "not_started", 0, ["理解构建、打包与 HMR 的原理","掌握代码分割与按需加载配置","能排查构建相关的问题"], ["HMR","代码分割"], ["配置一次按需加载与分包并说明收益"]),
      N("css-eng", "CSS 工程化", "🎨", "工程", 6, "Use", "not_started", 0, ["掌握 CSS 预处理器或原子化方案","掌握设计令牌与主题系统","能建立可维护的样式体系"], ["Tailwind","设计令牌"], ["用设计令牌重构一套主题样式"]),
      N("lint", "代码规范与 Lint", "🧹", "工程", 7, "Use", "not_started", 0, ["配置 ESLint/Prettier 统一代码风格","建立提交前检查与规范约束","能落地团队协作规范"], ["ESLint","Prettier"], ["为项目接入完整的 Lint 配置并纳入提交流程"]),
      N("modular", "模块化与代码分割", "🧱", "工程", 7, "Use", "not_started", 0, ["掌握 ESM 与打包产物的模块组织","理解动态导入与分包策略","能优化首屏加载"], ["ESM","动态导入"], ["优化一个项目的首屏加载速度"]),
      N("git", "版本控制 Git", "🌿", "工程", 2, "Use", "completed", 0, ["掌握常用 Git 命令与分支模型","理解合并、变基与冲突解决","掌握规范的提交信息"], ["分支","rebase"], ["独立完成一次多人协作开发流程"]),
      N("perf", "性能优化", "🚀", "进阶", 10, "Use", "not_started", 0, ["掌握首屏、交互与运行时性能优化手段","理解 Core Web Vitals 指标","能定位并优化性能瓶颈"], ["首屏","Core Web Vitals"], ["把某页面 LCP 显著降低并说明优化手段"]),
      N("security", "前端安全", "🛡️", "进阶", 8, "Understand", "not_started", 0, ["理解 XSS、CSRF、点击劫持等攻击","掌握防御性编码与安全响应头","理解依赖安全与 CSP"], ["XSS","CSRF","CSP"], ["指出一段代码的安全隐患并给出修复方案"]),
      N("testing", "单元测试", "✅", "进阶", 10, "Use", "not_started", 0, ["掌握组件测试与关键逻辑测试","理解测试金字塔与覆盖率","能写出稳定、可维护的测试"], ["测试金字塔","组件测试"], ["为一个组件补齐关键路径的测试"]),
      N("render-opt", "渲染优化", "🎞️", "进阶", 7, "Understand", "not_started", 0, ["理解浏览器渲染与合成优化","掌握减少重排重绘的技巧","理解虚拟列表与懒渲染"], ["合成","虚拟列表"], ["优化一个长列表的渲染性能"]),
      N("deploy", "部署与 CI/CD", "🚢", "进阶", 11, "Use", "not_started", 0, ["理解 CI/CD 流水线与静态托管","掌握监控与错误追踪","能把项目交付上线并可持续迭代"], ["CI/CD","监控"], ["把项目自动化部署并接入基础监控"]),
    ],
    edges: [
      E("html", "css-box"),
      E("css-box", "css-cascade"),
      E("css-box", "flexbox"),
      E("flexbox", "grid"),
      E("flexbox", "responsive"),
      E("grid", "responsive"),
      E("js-basic", "js-types"),
      E("js-basic", "js-func"),
      E("js-types", "js-array"),
      E("js-func", "js-closure"),
      E("js-func", "js-this"),
      E("js-func", "js-object"),
      E("js-array", "es6"),
      E("js-closure", "es6"),
      E("js-basic", "dom"),
      E("js-func", "dom"),
      E("es6", "dom"),
      E("dom", "event-loop"),
      E("dom", "browser"),
      E("es6", "promise"),
      E("promise", "async-await"),
      E("promise", "fetch-api"),
      E("fetch-api", "http"),
      E("dom", "web-storage"),
      E("es6", "typescript"),
      E("async-await", "debugging"),
      E("dom", "framework-core"),
      E("es6", "framework-core"),
      E("typescript", "framework-core"),
      E("framework-core", "react"),
      E("react", "state-props"),
      E("state-props", "hooks"),
      E("hooks", "state-mgmt"),
      E("react", "router"),
      E("hooks", "forms"),
      E("es6", "package"),
      E("package", "vite"),
      E("responsive", "css-eng"),
      E("vite", "lint"),
      E("vite", "modular"),
      E("js-basic", "git"),
      E("hooks", "perf"),
      E("browser", "render-opt"),
      E("render-opt", "perf"),
      E("http", "security"),
      E("framework-core", "security"),
      E("hooks", "testing"),
      E("vite", "deploy"),
      E("testing", "deploy"),
      E("perf", "deploy"),
    ]
  },
  backend: {
    tree: {"id":"backend","topic":"后端开发","title":"后端开发工程师技能树","description":"从语言与操作系统基础到数据库、缓存、分布式与高可用的完整后端路线(42 节点)。"},
    current: "framework",
    nodes: [
      N("lang-basic", "编程语言基础", "💻", "语言", 1, "Understand", "mastered", 0, ["扎实掌握一门后端语言的核心语法与编程范式","理解类型系统、异常处理与内存模型","能独立编写结构化、可读的程序"], ["类型系统","异常处理"], ["独立完成一个命令行小工具"]),
      N("ds", "数据结构基础", "📊", "基础", 2, "Understand", "mastered", 0, ["掌握数组、链表、哈希表、树等核心数据结构","理解各结构的时间/空间复杂度","能根据场景选择合适的数据结构"], ["链表","哈希表"], ["为不同场景选择合适结构并说明复杂度"]),
      N("algo", "算法基础", "🧮", "基础", 2, "Understand", "mastered", 0, ["掌握排序、查找与递归等基础算法","理解复杂度分析与常见优化","能解决常见的算法问题"], ["排序","复杂度"], ["独立实现并分析一个基础算法"]),
      N("os", "操作系统基础", "🧠", "基础", 2, "Understand", "mastered", 0, ["理解进程、线程与调度机制","理解内存管理与虚拟内存","理解文件系统与 I/O 模型"], ["进程线程","虚拟内存"], ["解释进程与线程的区别及切换代价"]),
      N("linux", "Linux 与命令行", "🐧", "基础", 3, "Use", "mastered", 0, ["熟练使用常用命令、管道与重定向","掌握 shell 脚本编写","能通过命令行排查线上问题"], ["shell","管道"], ["用一条命令完成日志过滤与统计"]),
      N("net", "计算机网络", "🕸️", "网络", 4, "Understand", "mastered", 0, ["理解 TCP/UDP 与三次握手四次挥手","理解拥塞控制与流量控制","理解 DNS、IP 与路由的基本原理"], ["TCP","拥塞控制"], ["解释 TIME_WAIT 状态及作用"]),
      N("http", "HTTP 协议", "🌐", "网络", 5, "Use", "completed", 0, ["掌握 HTTP 方法、状态码与报文结构","理解缓存机制与 HTTPS 证书","理解 HTTP/2 的改进"], ["HTTPS","缓存"], ["用抓包工具分析一次完整请求"]),
      N("sql", "SQL 与关系型数据库", "🗄️", "数据", 3, "Use", "completed", 0, ["熟练编写查询、连接与事务","理解索引原理与执行计划","掌握范式化设计"], ["索引","事务"], ["优化一条慢查询并说明索引选择"]),
      N("db-design", "数据库设计", "🗄️", "数据", 4, "Understand", "completed", 0, ["掌握 ER 建模与范式设计","理解反范式与性能权衡","能设计合理、可扩展的 schema"], ["ER 建模","范式"], ["为一个业务模块设计完整的表结构"]),
      N("nosql", "NoSQL 与 Redis", "🧊", "数据", 5, "Use", "completed", 0, ["掌握 Redis 的核心数据结构","理解缓存模式、过期与淘汰策略","理解持久化与集群"], ["缓存模式","持久化"], ["设计一个防击穿的缓存方案"]),
      N("framework", "后端框架", "🏗️", "框架", 6, "Use", "in_progress", 0, ["掌握 MVC/分层架构与中间件机制","理解请求生命周期与依赖注入","能搭建结构清晰的服务"], ["中间件","依赖注入"], ["用框架实现一个含鉴权的 CRUD 模块"]),
      N("api", "RESTful API 设计", "🔌", "框架", 7, "Use", "in_progress", 0, ["设计规范、可演进的接口","掌握版本化、错误码与幂等","掌握接口文档与测试"], ["版本化","幂等"], ["设计一套资源接口并给出完整文档"]),
      N("auth", "认证与授权", "🔐", "框架", 8, "Use", "not_started", 0, ["掌握 JWT、OAuth 与权限模型(RBAC)","理解会话管理与单点登录","能防常见认证攻击"], ["JWT","RBAC"], ["实现带角色权限的登录鉴权"]),
      N("validation", "数据校验", "✅", "框架", 8, "Use", "not_started", 0, ["掌握输入校验、清洗与类型约束","理解校验失败的处理策略","能防止注入与脏数据"], ["校验","防注入"], ["为接口建立完整的输入校验"]),
      N("orm", "ORM 与数据访问", "🗃️", "数据", 7, "Use", "not_started", 0, ["掌握 ORM 的映射与查询","理解 N+1 问题及其解决","掌握事务与行级锁"], ["ORM","N+1"], ["定位并解决一次 N+1 查询问题"]),
      N("middleware", "中间件机制", "🔗", "框架", 7, "Understand", "not_started", 0, ["理解中间件链与洋葱模型","能编写自定义中间件","理解错误处理中间件的职责"], ["洋葱模型","错误处理"], ["编写一个日志/鉴权中间件"]),
      N("logging", "日志与监控", "📊", "进阶", 7, "Use", "not_started", 0, ["建立结构化日志体系","掌握关键指标与告警","能通过日志快速定位问题"], ["结构化日志","告警"], ["为服务接入关键指标与告警"]),
      N("cache", "缓存策略", "⚡", "进阶", 6, "Use", "not_started", 0, ["掌握缓存一致性与更新策略","理解缓存穿透/击穿/雪崩","能设计稳健的缓存方案"], ["一致性","穿透击穿雪崩"], ["解决一次缓存与 DB 不一致的问题"]),
      N("mq", "消息队列", "📮", "进阶", 7, "Understand", "not_started", 0, ["理解异步解耦、削峰与可靠性投递","理解幂等、死信与重试机制","能设计可靠的异步方案"], ["削峰","幂等"], ["设计一个下单-扣库存的解耦方案"]),
      N("concurrency", "并发编程", "🌀", "进阶", 3, "Understand", "not_started", 0, ["理解并发模型、锁与竞态","理解死锁的成因与避免","能写并发安全的代码"], ["锁","死锁"], ["定位并修复一个并发 bug"]),
      N("transactions", "事务与一致性", "🔒", "数据", 4, "Understand", "not_started", 0, ["理解 ACID 与四种隔离级别","理解分布式事务与最终一致性","能权衡一致性与性能"], ["ACID","隔离级别"], ["解释各隔离级别及可能出现的异常"]),
      N("security", "Web 安全", "🛡️", "进阶", 6, "Understand", "not_started", 0, ["理解注入、XSS、CSRF、SSRF 等攻击","掌握安全编码与加密哈希","理解安全响应头"], ["注入","SSRF"], ["识别并修复一段代码的安全漏洞"]),
      N("testing", "后端测试", "🧪", "进阶", 7, "Use", "not_started", 0, ["掌握单元、集成与契约测试","理解测试隔离与 mock","建立可维护的测试策略"], ["测试隔离","mock"], ["为关键服务补齐单元与集成测试"]),
      N("docker", "容器化 Docker", "🐳", "部署", 7, "Use", "not_started", 0, ["编写 Dockerfile 并理解镜像分层","掌握容器编排与网络","能把服务打包为可复现容器"], ["镜像分层","编排"], ["把一个服务打包为可复现的容器"]),
      N("git", "版本控制与协作", "🌿", "工程", 2, "Use", "completed", 0, ["掌握分支模型与 Code Review 流程","理解合并、变基与冲突解决","掌握规范提交与发布"], ["分支模型","Code Review"], ["独立完成一次规范的协作开发流程"]),
      N("cicd", "CI/CD 流水线", "🔄", "部署", 8, "Use", "not_started", 0, ["搭建自动化构建、测试与发布流水线","理解灰度发布与回滚","实现提交后自动部署"], ["流水线","灰度"], ["实现提交后自动构建并部署"]),
      N("microservice", "微服务架构", "🧩", "进阶", 9, "Understand", "not_started", 0, ["理解服务拆分与治理","理解注册发现、熔断与限流","能权衡单体与微服务的取舍"], ["服务发现","熔断"], ["说明何时该拆分微服务的判断依据"]),
      N("gateway", "网关与负载均衡", "🚪", "进阶", 10, "Understand", "not_started", 0, ["理解反向代理与 API 网关","理解负载均衡算法与健康检查","理解限流与熔断的接入"], ["反向代理","负载均衡"], ["配置一套带健康检查的负载均衡"]),
      N("distributed", "分布式系统", "🌍", "进阶", 11, "Understand", "not_started", 0, ["理解 CAP 与一致性模型","理解分布式事务与分布式锁","理解分布式共识"], ["CAP","分布式事务"], ["解释 CAP 理论并给出工程权衡"]),
      N("rpc", "RPC 与通信", "📡", "进阶", 12, "Understand", "not_started", 0, ["理解 RPC 原理与序列化机制","掌握 gRPC 与 Protobuf","能设计高效的通信接口"], ["序列化","gRPC"], ["实现一个简单的 RPC 调用"]),
      N("deploy", "部署与运维", "🚀", "部署", 9, "Use", "not_started", 0, ["掌握部署策略与高可用","理解容灾与故障转移","掌握监控告警体系"], ["高可用","容灾"], ["部署一套带负载均衡与监控的服务"]),
      N("performance", "性能优化", "⚡", "进阶", 9, "Use", "not_started", 0, ["掌握性能分析与调优方法","理解瓶颈定位与压测","能针对性优化关键路径"], ["压测","瓶颈定位"], ["定位并优化一个性能瓶颈"]),
      N("observability", "可观测性", "🔭", "进阶", 8, "Understand", "not_started", 0, ["理解 Trace、Metrics、Logs 三支柱","建立分布式追踪","能快速定位链路问题"], ["Trace/Metrics/Logs","链路追踪"], ["为一次跨服务调用建立完整追踪"]),
      N("config", "配置管理", "⚙️", "工程", 7, "Use", "not_started", 0, ["掌握配置分层与环境隔离","理解密钥管理与安全存储","能安全地管理敏感配置"], ["环境隔离","密钥管理"], ["建立分环境、可回滚的配置体系"]),
      N("rate-limit", "限流与降级", "🚦", "进阶", 8, "Understand", "not_started", 0, ["理解令牌桶、漏桶等限流算法","掌握熔断与降级策略","能保障系统稳定性"], ["令牌桶","熔断"], ["实现一个限流器并说明算法选择"]),
      N("encryption", "加密与安全协议", "🔐", "进阶", 7, "Understand", "not_started", 0, ["理解对称/非对称加密与哈希","理解 TLS 握手过程","掌握密钥与证书管理"], ["对称/非对称加密","TLS"], ["解释 TLS 握手并识别证书问题"]),
      N("db-opt", "数据库优化", "📈", "数据", 8, "Use", "not_started", 0, ["掌握慢查询分析与优化","理解索引失效场景","理解分库分表与读写分离"], ["慢查询","分库分表"], ["优化一组慢查询并说明优化点"]),
      N("design-pattern", "设计模式", "🎯", "工程", 8, "Understand", "not_started", 0, ["掌握常用设计模式及适用场景","理解 SOLID 原则","能合理应用而非滥用"], ["SOLID","常用模式"], ["用设计模式重构一段坏味道代码"]),
      N("architecture", "架构设计", "🏛️", "进阶", 10, "Understand", "not_started", 0, ["理解分层、模块化与依赖管理","理解高内聚低耦合的实践","能设计清晰的系统架构"], ["分层","高内聚低耦合"], ["为一个小系统设计完整的架构图"]),
      N("scalability", "可扩展性", "📈", "进阶", 11, "Understand", "not_started", 0, ["理解水平扩展与分片","理解无状态设计与会话外置","能设计可水平扩展的系统"], ["水平扩展","无状态"], ["把一个有状态服务改造成可水平扩展"]),
      N("reliability", "可靠性与高可用", "🛡️", "进阶", 12, "Understand", "not_started", 0, ["理解冗余、容灾与故障转移","理解可用性指标与 SLO","能设计高可用架构"], ["冗余","SLO"], ["设计一个多副本高可用的服务拓扑"]),
      N("capstone", "综合后端项目", "🏆", "进阶", 13, "Use", "not_started", 0, ["综合运用所学构建完整后端系统","贯穿需求、设计、开发、测试与部署","能独立交付生产级服务"], ["全链路","生产级"], ["独立交付一个从设计到上线的完整后端项目"]),
    ],
    edges: [
      E("lang-basic", "ds"),
      E("lang-basic", "algo"),
      E("lang-basic", "os"),
      E("os", "linux"),
      E("os", "net"),
      E("linux", "net"),
      E("net", "http"),
      E("ds", "sql"),
      E("sql", "db-design"),
      E("db-design", "nosql"),
      E("sql", "nosql"),
      E("sql", "framework"),
      E("http", "framework"),
      E("framework", "api"),
      E("api", "auth"),
      E("api", "validation"),
      E("sql", "orm"),
      E("framework", "orm"),
      E("framework", "middleware"),
      E("framework", "logging"),
      E("nosql", "cache"),
      E("framework", "mq"),
      E("os", "concurrency"),
      E("sql", "transactions"),
      E("http", "security"),
      E("framework", "testing"),
      E("framework", "docker"),
      E("docker", "cicd"),
      E("lang-basic", "git"),
      E("auth", "microservice"),
      E("mq", "microservice"),
      E("microservice", "gateway"),
      E("gateway", "distributed"),
      E("distributed", "rpc"),
      E("cicd", "deploy"),
      E("logging", "deploy"),
      E("cache", "distributed"),
      E("logging", "observability"),
      E("observability", "performance"),
      E("framework", "config"),
      E("config", "rate-limit"),
      E("rate-limit", "reliability"),
      E("security", "encryption"),
      E("orm", "db-opt"),
      E("db-opt", "performance"),
      E("api", "design-pattern"),
      E("microservice", "architecture"),
      E("architecture", "scalability"),
      E("scalability", "reliability"),
      E("deploy", "capstone"),
      E("reliability", "capstone"),
      E("performance", "capstone"),
    ]
  },
  algorithm: {
    tree: {"id":"algorithm","topic":"算法","title":"算法与数据结构技能树","description":"从复杂度与基础结构到图论、动态规划与高级算法的完整刷题进阶路线(40 节点)。"},
    current: "graph",
    nodes: [
      N("complexity", "复杂度分析", "⏱️", "入门", 1, "Understand", "mastered", 0, ["掌握时间/空间复杂度的推导与比较","理解最好/最坏/均摊复杂度","能用大 O 记号准确描述算法开销"], ["大O","均摊"], ["推导一段代码的复杂度并说明最坏情况"]),
      N("array", "数组与链表", "🔗", "基础", 2, "Use", "mastered", 0, ["掌握数组与链表的操作与取舍","理解虚拟头结点、快慢指针等技巧","能解决反转、合并等经典问题"], ["指针","虚拟头结点"], ["手写链表反转、合并与环检测"]),
      N("stack", "栈与队列", "📚", "基础", 3, "Use", "mastered", 0, ["掌握栈与队列的特性与应用","掌握单调栈/单调队列","能解决括号匹配、接雨水等经典问题"], ["单调栈","单调队列"], ["用单调栈解决接雨水问题"]),
      N("string-basic", "字符串基础", "🔤", "基础", 2, "Use", "mastered", 0, ["掌握字符串的遍历、比较与常用操作","理解字符编码与回文等基本性质","能解决基础字符串问题"], ["字符编码","回文"], ["解决字符串反转与回文判定问题"]),
      N("hash", "哈希表", "🗃️", "基础", 3, "Use", "mastered", 0, ["理解哈希函数、冲突解决与查找均摊复杂度","掌握哈希表的灵活应用","能用哈希优化查找类问题"], ["冲突","均摊"], ["实现两数之和并说明哈希为何高效"]),
      N("tree", "树与二叉树", "🌳", "基础", 3, "Use", "completed", 0, ["掌握树的遍历(前中后序、层序)","理解二叉搜索树性质","掌握递归与迭代两种实现"], ["遍历","BST"], ["写出三种遍历的递归与迭代版本"]),
      N("sort", "排序算法", "↕️", "基础", 4, "Use", "completed", 0, ["掌握快排、归并与堆排序","理解稳定性与复杂度","能手写并比较各排序算法"], ["快排","归并"], ["手写快排并说明最坏复杂度与优化"]),
      N("binary", "二分查找", "🎯", "基础", 5, "Use", "completed", 0, ["掌握二分模板与边界处理","能解决变体问题","理解二分的适用条件"], ["边界","变体"], ["实现寻找旋转数组的最小值"]),
      N("twoptr", "双指针", "👣", "技巧", 3, "Use", "completed", 0, ["掌握同向/对撞双指针","掌握双指针在有序数据中的应用","能解决两数之和、接雨水变体等"], ["对撞","滑动"], ["用对撞双指针解决三数之和"]),
      N("sliding", "滑动窗口", "🪟", "技巧", 3, "Use", "completed", 0, ["掌握滑动窗口的框架与收缩条件","理解窗口的单调性","能解决最长/最短子串类问题"], ["窗口","收缩"], ["用滑动窗口求最长无重复子串"]),
      N("prefix", "前缀和与差分", "➕", "技巧", 3, "Use", "completed", 0, ["掌握前缀和与差分的原理","理解区间和的快速求解","能解决区间统计类问题"], ["前缀和","差分"], ["用前缀和解决区间求和问题"]),
      N("heap", "堆与优先队列", "⛰️", "基础", 4, "Use", "completed", 0, ["理解堆结构与堆化过程","掌握 Top-K 问题","能手写堆并理解优先队列"], ["堆化","Top-K"], ["用堆求前 K 大元素并说明复杂度"]),
      N("graph", "图基础与表示", "🕸️", "图论", 5, "Understand", "in_progress", 0, ["理解图的邻接表/邻接矩阵表示","理解连通性、度与环","掌握图的遍历基础"], ["邻接表","连通性"], ["用邻接表建模一个实际问题"]),
      N("recursion", "递归思想", "🔁", "基础", 1, "Understand", "mastered", 0, ["理解递归三要素与递归树","理解递归与栈的关系","能写出正确的递归"], ["递归树","递归出口"], ["分析一个递归的时间复杂度"]),
      N("backtrack", "回溯算法", "🔙", "技巧", 4, "Use", "in_progress", 0, ["掌握回溯模板与剪枝","能解组合、排列、子集问题","理解状态回退"], ["剪枝","排列"], ["解决 N 皇后或全排列问题"]),
      N("dfs", "深度优先搜索", "🧗", "图论", 6, "Use", "not_started", 0, ["掌握 DFS 的递归与迭代实现","理解 DFS 解决路径、连通分量问题","能处理回溯式搜索"], ["连通分量","路径"], ["解决岛屿数量问题"]),
      N("bfs", "广度优先搜索", "🌊", "图论", 6, "Use", "not_started", 0, ["掌握 BFS 的分层遍历","理解 BFS 求最短路径","掌握多源 BFS"], ["分层","最短路"], ["求网格中的最短路径"]),
      N("greedy", "贪心算法", "🍬", "进阶", 1, "Use", "not_started", 0, ["理解贪心的适用条件与正确性","掌握区间调度等经典贪心","能判断何时贪心成立"], ["区间调度","正确性"], ["解决区间合并问题"]),
      N("unionfind", "并查集", "🔗", "图论", 6, "Use", "not_started", 0, ["掌握并查集的查找与合并","理解路径压缩与按秩合并","能解决连通性问题"], ["路径压缩","按秩合并"], ["解决朋友圈/省份数量问题"]),
      N("shortest", "最短路算法", "🛣️", "图论", 7, "Use", "not_started", 0, ["掌握 Dijkstra 算法","理解负权边与适用场景","能用优先队列优化"], ["Dijkstra","优先队列"], ["实现带权图的单源最短路"]),
      N("topo", "拓扑排序", "🔝", "图论", 6, "Use", "not_started", 0, ["理解拓扑排序与依赖关系","掌握 Kahn 与 DFS 两种实现","能解决课程表类问题"], ["Kahn","依赖"], ["解决课程表(检测环)问题"]),
      N("mst", "最小生成树", "🌲", "图论", 7, "Use", "not_started", 0, ["掌握 Kruskal 与 Prim 算法","理解并查集在 Kruskal 中的作用","能解决连通成本问题"], ["Kruskal","Prim"], ["实现最小生成树并说明复杂度"]),
      N("dp-basic", "动态规划入门", "🧩", "DP", 2, "Use", "not_started", 0, ["掌握状态定义与转移方程","理解记忆化搜索与递推","能解决爬楼梯、打家劫舍等入门题"], ["状态转移","记忆化"], ["解决爬楼梯与打家劫舍"]),
      N("dp-classic", "经典 DP", "🧠", "DP", 3, "Use", "not_started", 0, ["掌握最长递增子序列、LCS 等经典模型","理解状态设计的常见套路","能迁移解决变体问题"], ["LIS","LCS"], ["解决最长公共子序列问题"]),
      N("dp-advanced", "高级 DP", "🧠", "DP", 4, "Use", "not_started", 0, ["掌握多状态与多维 DP","理解状态压缩思路","能处理复杂的状态设计"], ["多维 DP","状态设计"], ["解决股票买卖系列问题"]),
      N("knapsack", "背包问题", "🎒", "DP", 3, "Use", "not_started", 0, ["掌握 01 背包与完全背包","理解二维到一维的优化","能识别背包类问题"], ["01背包","完全背包"], ["解决经典背包及其变体"]),
      N("interval-dp", "区间 DP", "📐", "DP", 4, "Use", "not_started", 0, ["掌握区间 DP 的枚举套路","理解合并类问题","能解决石子合并等"], ["区间合并","枚举"], ["解决石子合并问题"]),
      N("bitmask", "状态压缩 DP", "💡", "DP", 5, "Use", "not_started", 0, ["掌握位运算表示状态","理解状态压缩 DP 的转移","能解决旅行商等 NP 类小规模问题"], ["状态压缩","位运算"], ["解决旅行商问题(TSP)"]),
      N("bit", "位运算", "💡", "技巧", 3, "Use", "not_started", 0, ["掌握与或非异或及移位","掌握常见位运算技巧","能用位运算优化与解题"], ["掩码","异或"], ["用位运算解决只出现一次的数字"]),
      N("string-algo", "字符串算法", "🔤", "进阶", 3, "Understand", "not_started", 0, ["理解字符串哈希与滚动哈希","掌握常见字符串处理技巧","能解决子串匹配类问题"], ["滚动哈希","子串"], ["用滚动哈希解决重复子串检测"]),
      N("kmp", "KMP 与匹配", "🔤", "进阶", 4, "Understand", "not_started", 0, ["理解 next 数组与失配跳转","掌握 KMP 的线性匹配","能解释为何避免回溯"], ["next数组","失配"], ["手写 KMP 并说明线性复杂度"]),
      N("trie", "字典树", "🌳", "进阶", 4, "Use", "not_started", 0, ["掌握字典树的构建与查询","理解前缀匹配与统计","能解决前缀类问题"], ["前缀","插入查询"], ["实现一个支持前缀查询的字典树"]),
      N("segment-tree", "线段树", "🌲", "高级", 4, "Use", "not_started", 0, ["理解线段树的区间维护","掌握区间查询与更新","能解决区间最值/求和问题"], ["区间查询","懒标记"], ["实现带懒标记的区间更新"]),
      N("fenwick", "树状数组", "🌲", "高级", 5, "Use", "not_started", 0, ["理解树状数组的 lowbit 原理","掌握单点更新与区间查询","能解决逆序对等计数问题"], ["lowbit","区间和"], ["用树状数组求逆序对"]),
      N("math", "数学与数论", "🔢", "进阶", 2, "Understand", "not_started", 0, ["掌握素数、最大公约数与快速幂","理解模运算性质","能解决基础数论问题"], ["快速幂","gcd"], ["实现快速幂与筛法求素数"]),
      N("combinatorics", "组合数学", "🎲", "进阶", 3, "Understand", "not_started", 0, ["掌握排列组合与容斥原理","理解常见组合计数","能解决计数类问题"], ["容斥","计数"], ["解决一个组合计数问题"]),
      N("advanced-ds", "高级数据结构", "🏗️", "高级", 4, "Understand", "not_started", 0, ["理解平衡树、跳表等高级数据结构的原理","理解其适用场景与时间复杂度","能根据业务场景合理选型并说明理由"], ["平衡树","跳表"], ["解释高级结构适用场景并选型"]),
      N("advanced-algo", "高级算法思想", "🧠", "高级", 5, "Understand", "not_started", 0, ["理解分治、倍增、扫描线等思想","理解其适用场景","能综合运用解决复杂问题"], ["分治","扫描线"], ["用分治思想解决一个复杂问题"]),
      N("contest", "竞赛与刷题技巧", "🏆", "高级", 6, "Use", "not_started", 0, ["掌握题目分类与套路识别","理解时间复杂度的选择","能稳定通过中高难度题目"], ["套路识别","复杂度"], ["稳定通过一道中等偏难题"]),
      N("interview", "面试算法", "🎯", "高级", 7, "Use", "not_started", 0, ["掌握高频面试题的解法与讲法","理解边写边讲的表达","能在压力下稳定发挥"], ["高频题","表达"], ["在限时内讲解并写出一道高频题"]),
    ],
    edges: [
      E("complexity", "array"),
      E("complexity", "string-basic"),
      E("array", "stack"),
      E("array", "hash"),
      E("string-basic", "hash"),
      E("array", "tree"),
      E("recursion", "tree"),
      E("tree", "sort"),
      E("stack", "sort"),
      E("sort", "binary"),
      E("array", "twoptr"),
      E("array", "sliding"),
      E("array", "prefix"),
      E("tree", "heap"),
      E("heap", "graph"),
      E("tree", "graph"),
      E("recursion", "backtrack"),
      E("tree", "backtrack"),
      E("graph", "dfs"),
      E("graph", "bfs"),
      E("backtrack", "dfs"),
      E("greedy", "dp-basic"),
      E("graph", "unionfind"),
      E("graph", "shortest"),
      E("bfs", "shortest"),
      E("graph", "topo"),
      E("unionfind", "mst"),
      E("graph", "mst"),
      E("recursion", "dp-basic"),
      E("dp-basic", "dp-classic"),
      E("dp-classic", "dp-advanced"),
      E("dp-basic", "knapsack"),
      E("dp-classic", "interval-dp"),
      E("dp-advanced", "bitmask"),
      E("array", "bit"),
      E("string-basic", "string-algo"),
      E("string-algo", "kmp"),
      E("hash", "trie"),
      E("tree", "trie"),
      E("array", "segment-tree"),
      E("tree", "segment-tree"),
      E("segment-tree", "fenwick"),
      E("bit", "fenwick"),
      E("complexity", "math"),
      E("math", "combinatorics"),
      E("tree", "advanced-ds"),
      E("advanced-ds", "advanced-algo"),
      E("advanced-algo", "contest"),
      E("dp-advanced", "contest"),
      E("contest", "interview"),
    ]
  },
  "ai-agent": {
    tree: {"id":"ai-agent","topic":"AI Agent","title":"AI Agent 开发技能树","description":"从 Python 与机器学习基础到 LLM、RAG、Agent 框架与生产化的完整路线(40 节点)。"},
    current: "rag",
    nodes: [
      N("py-basic", "Python 语法基础", "🐍", "语言", 1, "Understand", "mastered", 0, ["掌握 Python 语法、内置类型与流程控制","理解缩进与代码块的语义","能把其他语言逻辑改写为等价 Python"], ["缩进","内置类型"], ["把一段 JS 逻辑改写为等价 Python 并跑通"]),
      N("py-ds", "Python 数据结构", "📊", "语言", 2, "Use", "mastered", 0, ["熟练使用 list/dict/tuple/set 及推导式","理解可变与不可变类型","能高效处理数据"], ["推导式","可变性"], ["用推导式与容器完成一次数据整理"]),
      N("py-oop", "面向对象", "🏛️", "语言", 2, "Use", "mastered", 0, ["掌握类、继承、多态与魔术方法","理解属性与方法的组织","能组织可维护的类结构"], ["继承","魔术方法"], ["用面向对象组织一个多模块小项目"]),
      N("py-func", "函数式与迭代器", "🔁", "语言", 3, "Use", "completed", 0, ["掌握高阶函数、装饰器与生成器","理解迭代器协议与惰性求值","能写出 Pythonic 的代码"], ["装饰器","生成器"], ["用装饰器与生成器重构一段代码"]),
      N("py-stdlib", "标准库与异常", "📚", "语言", 2, "Use", "completed", 0, ["熟练使用 os/json/pathlib 等常用模块","掌握异常处理与上下文管理器","能编写健壮的脚本"], ["标准库","上下文管理器"], ["编写一个健壮的文件处理脚本"]),
      N("py-env", "环境与包管理", "📦", "语言", 3, "Use", "completed", 0, ["掌握 venv/conda 等环境隔离","掌握 pip 与依赖锁定","能复现一致的开发环境"], ["venv","依赖锁定"], ["为项目建立可复现的环境与依赖"]),
      N("linalg", "线性代数", "📐", "数学", 1, "Understand", "mastered", 0, ["掌握向量、矩阵运算与线性变换","理解特征值与特征向量","支撑后续模型理解"], ["矩阵","特征值"], ["手算矩阵乘法并解释特征向量的含义"]),
      N("calc", "微积分基础", "📈", "数学", 2, "Understand", "completed", 0, ["理解导数、偏导与梯度","理解链式法则","支撑反向传播理解"], ["梯度","链式法则"], ["手推一个复合函数的梯度"]),
      N("prob", "概率与统计", "🎲", "数学", 3, "Understand", "completed", 0, ["理解分布、期望与方差","理解最大似然与交叉熵","支撑模型训练与评估"], ["分布","最大似然"], ["解释交叉熵与最大似然的关系"]),
      N("numpy", "NumPy", "🔢", "数据", 4, "Use", "completed", 0, ["熟练使用 NumPy 的向量化运算","理解广播机制与索引","能高效处理数值数据"], ["向量化","广播"], ["用向量化替代显式循环并说明收益"]),
      N("pandas", "Pandas", "🐼", "数据", 5, "Use", "completed", 0, ["熟练使用 DataFrame 的筛选、分组与聚合","掌握缺失值处理","能完成数据清洗分析"], ["DataFrame","分组聚合"], ["清洗并聚合一份真实数据集"]),
      N("ml-basic", "机器学习基础", "🤖", "ML", 6, "Understand", "completed", 0, ["理解监督/无监督学习范式","理解过拟合、欠拟合与正则化","理解训练/验证/测试划分"], ["过拟合","正则化"], ["解释过拟合的成因与缓解手段"]),
      N("ml-algo", "经典机器学习算法", "🤖", "ML", 7, "Understand", "completed", 0, ["掌握线性回归、逻辑回归、决策树等","理解 SVM、集成学习的基本思想","能选择合适算法"], ["回归","集成学习"], ["为一个分类问题选择算法并说明理由"]),
      N("ml-eval", "模型评估与调优", "📏", "ML", 8, "Use", "completed", 0, ["掌握精确率、召回率、F1、AUC 等指标","掌握交叉验证与超参调优","能正确评估模型"], ["指标","交叉验证"], ["正确评估一个模型并说明指标选择"]),
      N("nn", "神经网络基础", "🧠", "DL", 7, "Understand", "completed", 0, ["理解前向/反向传播","理解激活函数与损失函数","理解优化器与学习率"], ["反向传播","优化器"], ["手写一个单层网络并训练"]),
      N("dl-framework", "深度学习框架", "🔥", "DL", 8, "Use", "in_progress", 0, ["熟练使用 PyTorch 建模与训练","理解自动求导与张量操作","能复现经典模型"], ["PyTorch","自动求导"], ["用框架复现一个经典模型"]),
      N("cnn", "CNN 与视觉", "👁️", "DL", 9, "Understand", "not_started", 0, ["理解卷积、池化与感受野","理解经典 CNN 结构","能处理视觉任务"], ["卷积","感受野"], ["解释卷积为何适合图像特征提取"]),
      N("rnn", "RNN 与序列", "📜", "DL", 9, "Understand", "not_started", 0, ["理解 RNN 与序列建模","理解 LSTM/GRU 的门控机制","理解注意力引入的动机"], ["LSTM","门控"], ["解释 LSTM 如何缓解梯度消失"]),
      N("llm-basic", "大模型基础", "🧬", "LLM", 8, "Understand", "in_progress", 0, ["理解语言建模与预训练目标","理解指令微调与对齐","理解模型能力与局限(幻觉)"], ["预训练","微调"], ["解释 LLM 为何会幻觉及缓解思路"]),
      N("transformer", "Transformer 架构", "⚙️", "LLM", 9, "Understand", "not_started", 0, ["理解自注意力、多头注意力与位置编码","理解残差与层归一化","能画出完整结构"], ["自注意力","位置编码"], ["画出 Transformer 结构并解释注意力计算"]),
      N("llm-training", "预训练与微调", "🔬", "LLM", 10, "Understand", "not_started", 0, ["理解预训练的数据与训练目标","理解 LoRA、QLoRA 等高效微调","理解全参微调的代价"], ["LoRA","高效微调"], ["说明何时选 LoRA 而非全参微调"]),
      N("prompt", "Prompt 工程", "✍️", "LLM", 9, "Use", "not_started", 0, ["掌握少样本、角色设定与结构化输出","理解提示词稳定性的重要性","能为任务设计可复用提示词"], ["少样本","结构化输出"], ["为一个任务设计稳定可复用的提示词"]),
      N("cot", "思维链与推理", "🧠", "LLM", 10, "Use", "not_started", 0, ["理解 CoT 与多步推理","掌握自一致性等增强技巧","能引导模型分步推理"], ["CoT","自一致性"], ["用 CoT 提升一个复杂任务的准确率"]),
      N("embedding", "向量与 Embedding", "🧭", "RAG", 9, "Use", "not_started", 0, ["理解向量表征与语义相似度","掌握常见 Embedding 模型","能实现语义检索"], ["向量检索","相似度"], ["实现一个语义相似度检索"]),
      N("vector-db", "向量数据库", "🗄️", "RAG", 10, "Use", "not_started", 0, ["理解向量索引(如 HNSW)与近似检索","掌握向量库的写入与查询","能选型合适的向量库"], ["HNSW","近似检索"], ["为检索场景选择合适的向量库"]),
      N("rag", "RAG 检索增强", "📚", "RAG", 11, "Use", "in_progress", 0, ["掌握切分、召回、重排与引用溯源","理解混合检索与上下文组织","能搭建可溯源的 RAG 流程"], ["召回","重排"], ["搭建一个可溯源的问答 RAG 系统"]),
      N("rag-advanced", "RAG 进阶优化", "📚", "RAG", 12, "Use", "not_started", 0, ["掌握查询改写、多路召回与精排","理解评估与迭代优化","能显著提升检索质量"], ["查询改写","多路召回"], ["优化一个 RAG 系统的检索命中率"]),
      N("function-call", "Function Calling", "🔧", "Agent", 10, "Use", "not_started", 0, ["掌握工具调用与结构化参数","理解循环调用与终止条件","能让模型稳定调用自定义工具"], ["工具调用","参数Schema"], ["让模型稳定调用一个自定义工具"]),
      N("agent-basic", "Agent 基础", "🕹️", "Agent", 11, "Understand", "not_started", 0, ["理解感知-规划-行动循环","理解工具、记忆与规划的关系","能解释 Agent 与普通 LLM 的区别"], ["感知规划行动","记忆"], ["解释 Agent 的完整工作循环"]),
      N("react-pattern", "ReAct 模式", "🔁", "Agent", 12, "Use", "not_started", 0, ["理解 ReAct 的推理-行动交替","掌握思考与工具的衔接","能实现一个 ReAct Agent"], ["推理行动交替","工具衔接"], ["实现一个能调用工具的 ReAct Agent"]),
      N("memory", "记忆机制", "🧠", "Agent", 13, "Understand", "not_started", 0, ["理解短期/长期记忆与上下文窗口","掌握记忆的检索与压缩","能设计有效的记忆方案"], ["短期长期记忆","压缩"], ["设计一个带记忆的多轮 Agent"]),
      N("langchain", "Agent 框架", "🧩", "Agent", 12, "Use", "not_started", 0, ["熟练用 LangChain 编排工具与链","理解抽象与常见组件","能搭建多工具 Agent"], ["编排","链"], ["用框架搭建一个多工具 Agent"]),
      N("langgraph", "图编排与状态机", "🕸️", "Agent", 13, "Use", "not_started", 0, ["掌握图式流程、状态与条件分支","理解循环与并发节点","能编排多步工作流"], ["状态图","条件边"], ["用图编排一个多步 Agent 工作流"]),
      N("mcp", "MCP 协议", "🔌", "Agent", 14, "Understand", "not_started", 0, ["理解 MCP 的工具/资源/提示抽象","理解客户端与服务端交互","能接入外部能力"], ["工具抽象","资源"], ["接入一个 MCP 服务并调用其工具"]),
      N("multi-agent", "多 Agent 协作", "👥", "Agent", 14, "Understand", "not_started", 0, ["理解角色分工、通信与编排模式","理解任务分解与聚合","能设计多 Agent 协作方案"], ["角色分工","通信"], ["设计一个多 Agent 协作的流程"]),
      N("eval", "评估与测试", "📏", "生产", 15, "Use", "not_started", 0, ["建立 Agent 的评测集与回归","掌握自动与人工评估","能衡量并持续改进回答质量"], ["评测集","回归"], ["为一组任务建立可复现的评测"]),
      N("observability", "可观测性", "🔭", "生产", 16, "Use", "not_started", 0, ["建立 Agent 的调用追踪与指标","理解成本与延迟监控","能快速定位链路问题"], ["调用追踪","成本监控"], ["为一个 Agent 建立完整追踪"]),
      N("prod", "生产化部署", "🚀", "生产", 17, "Use", "not_started", 0, ["掌握流式、缓存、限流与并发","理解可观测性与容错","能上线稳定的 Agent 服务"], ["流式","限流"], ["把一个 Agent 部署为可监控的服务"]),
      N("safety", "安全与对齐", "🛡️", "生产", 15, "Understand", "not_started", 0, ["理解提示注入、越狱与内容安全","理解对齐与红队测试","能加有效防护"], ["提示注入","对齐"], ["识别并防护一次提示注入攻击"]),
      N("capstone", "综合 Agent 项目", "🏆", "生产", 18, "Use", "not_started", 0, ["综合运用所学构建完整 Agent 应用","贯穿设计、开发、评估与部署","能独立交付可用的 Agent 产品"], ["全链路","交付"], ["独立交付一个从设计到上线的 Agent 应用"]),
    ],
    edges: [
      E("py-basic", "py-ds"),
      E("py-basic", "py-oop"),
      E("py-oop", "py-func"),
      E("py-ds", "py-func"),
      E("py-basic", "py-stdlib"),
      E("py-stdlib", "py-env"),
      E("linalg", "calc"),
      E("calc", "prob"),
      E("py-ds", "numpy"),
      E("prob", "numpy"),
      E("numpy", "pandas"),
      E("pandas", "ml-basic"),
      E("prob", "ml-basic"),
      E("linalg", "ml-basic"),
      E("ml-basic", "ml-algo"),
      E("ml-algo", "ml-eval"),
      E("ml-basic", "nn"),
      E("calc", "nn"),
      E("nn", "dl-framework"),
      E("dl-framework", "cnn"),
      E("dl-framework", "rnn"),
      E("prob", "llm-basic"),
      E("nn", "llm-basic"),
      E("llm-basic", "transformer"),
      E("transformer", "llm-training"),
      E("llm-basic", "prompt"),
      E("prompt", "cot"),
      E("dl-framework", "embedding"),
      E("embedding", "vector-db"),
      E("vector-db", "rag"),
      E("prompt", "rag"),
      E("rag", "rag-advanced"),
      E("prompt", "function-call"),
      E("llm-basic", "agent-basic"),
      E("function-call", "agent-basic"),
      E("agent-basic", "react-pattern"),
      E("react-pattern", "memory"),
      E("agent-basic", "langchain"),
      E("langchain", "langgraph"),
      E("langgraph", "mcp"),
      E("langgraph", "multi-agent"),
      E("rag-advanced", "eval"),
      E("multi-agent", "eval"),
      E("react-pattern", "eval"),
      E("eval", "observability"),
      E("observability", "prod"),
      E("function-call", "safety"),
      E("multi-agent", "safety"),
      E("prod", "capstone"),
      E("safety", "capstone"),
    ]
  }
};
