# Generated by Django 6.0.7 on 2026-07-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像URL')),
                ('voice_id', models.CharField(default='zh-CN-XiaoxiaoNeural', max_length=50, verbose_name='TTS语音ID')),
                ('voice_rate', models.CharField(default='+0%', max_length=10, verbose_name='语速')),
                ('style', models.CharField(default='teacher', max_length=100, verbose_name='风格')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'character',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('fill', '填空题'), ('short', '简答题')], default='single', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10)),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项列表')),
                ('correct_answer', models.JSONField(verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('score', models.PositiveSmallIntegerField(default=10, verbose_name='分值')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='搜索内容')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='结果数')),
                ('has_attachment', models.BooleanField(default=False, verbose_name='是否含附件')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('score_earned', models.PositiveSmallIntegerField(default=0, verbose_name='得分')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.quiz')),
            ],
            options={
                'db_table': 'quiz_submission',
            },
        ),
        migrations.CreateModel(
            name='VideoGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='搜索输入')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('analyzing', '正在分析'), ('scripting', '编写剧本'), ('rendering', '生成场景'), ('synthesizing', '合成视频'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度百分比')),
                ('total_scenes', models.PositiveSmallIntegerField(default=5, verbose_name='总场景数')),
                ('completed_scenes', models.PositiveSmallIntegerField(default=0, verbose_name='已完成场景数')),
                ('output_video', models.FileField(blank=True, upload_to='videos/', verbose_name='输出视频')),
                ('quality', models.CharField(choices=[('720p', '标清 720p'), ('1080p', '高清 1080p')], default='1080p', max_length=10)),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='视频时长(秒)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
            ],
            options={
                'db_table': 'video_generation',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.videogeneration'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_index', models.PositiveSmallIntegerField(verbose_name='场景序号')),
                ('scene_description', models.TextField(verbose_name='场景描述')),
                ('script_text', models.TextField(verbose_name='台词/字幕')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='场景图')),
                ('audio', models.FileField(blank=True, upload_to='audio/', verbose_name='配音音频')),
                ('duration', models.FloatField(default=5.0, verbose_name='时长(秒)')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.videogeneration')),
            ],
            options={
                'db_table': 'scene',
                'ordering': ['task', 'scene_index'],
                'unique_together': {('task', 'scene_index')},
            },
        ),
    ]
